In [57]:
import pandas as pd
import numpy as np
df=pd.read_csv('glass.csv')
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [58]:
x=df.iloc[:,0:9]
x

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 9 columns]

In [59]:
y=df.iloc[:,9:10]
y

Type
0       1
1       1
2       1
3       1
4       1
..    ...
209     7
210     7
211     7
212     7
213     7

[214 rows x 1 columns]

In [60]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss_out=ss.fit_transform(x)
x=ss_out

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [62]:
from sklearn.tree import DecisionTreeClassifier
obj=DecisionTreeClassifier(criterion='entropy')
output=obj.fit(x_train,y_train)
output1=output.predict(x_test)
output1

array([2, 5, 1, 7, 7, 5, 5, 1, 2, 1, 2, 2, 1, 2, 7, 3, 6, 1, 7, 2, 7, 1,
       7, 7, 1, 2, 5, 2, 6, 7, 1, 3, 2, 2, 2, 2, 2, 7, 1, 1, 3, 1, 1, 2,
       5, 1, 1, 1, 3, 7, 2, 1, 1, 1, 7, 2, 1, 3, 2, 2, 1, 7, 1, 2, 7],
      dtype=int64)

In [63]:
from sklearn.model_selection import cross_val_score
z=cross_val_score(estimator=obj,X=x_train,y=y_train,cv=5)
z

array([0.63333333, 0.63333333, 0.6       , 0.66666667, 0.68965517])

In [64]:
from sklearn.ensemble import RandomForestClassifier
fc=RandomForestClassifier(n_estimators=2)
a=fc.fit(x_train,y_train)
b=a.predict(x_test)
b

C:\Users\hp\AppData\Local\Temp/ipykernel_3580/4050723269.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  a=fc.fit(x_train,y_train)


array([2, 7, 1, 7, 7, 5, 2, 1, 2, 1, 2, 1, 1, 2, 7, 1, 1, 1, 7, 2, 7, 1,
       7, 7, 1, 2, 5, 2, 3, 1, 1, 3, 1, 2, 2, 2, 3, 2, 1, 2, 2, 1, 1, 2,
       5, 1, 1, 2, 2, 7, 2, 1, 1, 1, 1, 5, 1, 3, 2, 2, 1, 7, 1, 2, 7],
      dtype=int64)

In [65]:
x_train=pd.DataFrame(x_train)
x_train

0         1         2         3         4         5         6  \
0    0.051020  0.837308 -0.343656  0.431826  0.024673 -0.763919  0.255692   
1   -0.156917 -0.267402  0.844641 -0.290918 -0.415323  0.081369 -0.364103   
2    1.041198 -0.439246  0.670914 -1.154195 -0.557675 -0.471910  0.628977   
3   -0.166819 -0.832031  0.518033 -0.511756  0.387022  0.188951 -0.138723   
4    0.008113 -0.684737  0.684812 -0.411375 -0.104738  0.188951 -0.195068   
..        ...       ...       ...       ...       ...       ...       ...   
144 -0.199825  0.149933  0.504135  0.150759 -0.790614  0.127475 -0.117594   
145 -2.051456 -0.512893  0.545830 -0.652289  0.425846  0.188951 -0.427491   
146 -0.272438 -0.021911  0.677863 -0.511756  0.179965  0.112107 -0.483836   
147 -0.737821  0.628641  0.580575 -0.391299  0.296435 -0.195271 -0.716259   
148  1.107210  0.088560  0.733456 -1.093966 -0.829438 -0.487279  0.459942   

            7         8  
0   -0.352877 -0.586451  
1   -0.352877  2.293888  
2   -0.352877  1.162326  
3   -0.352877  2.499627  
4   -0.352877  3.013973  
..        ...       ...  
144 -0.352877 -0.586451  
145 -0.352877  2.602496  
146 -0.352877  0.545111  
147 -0.352877  0.853719  
148 -0.352877  0.133634  

[149 rows x 9 columns]

In [66]:
from sklearn.model_selection import GridSearchCV
a= GridSearchCV(estimator=fc,param_grid={'n_estimators':[1,2,4,6,8,10]},scoring='accuracy',cv= 5)
a.fit(x_train,y_train)
a.best_params_

C:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change

{'n_estimators': 8}